cors:
  origin-patterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr3t7
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
